/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.main.view;
//import com.main.service;

/**
 *
 * @author home
 */
public class mainframe extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menunewaccount = new javax.swing.JMenuItem();
        menunewtransaction = new javax.swing.JMenuItem();
        menuprintpassbook = new javax.swing.JMenuItem();
        menudeleteaccount = new javax.swing.JMenuItem();
        menuexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/main/image/sbilogo.jpg"))); // NOI18N

        jMenu1.setText("process");

        menunewaccount.setText("New account");
        menunewaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunewaccountActionPerformed(evt);
            }
        });
        jMenu1.add(menunewaccount);

        menunewtransaction.setText("New Transaction");
        menunewtransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunewtransactionActionPerformed(evt);
            }
        });
        jMenu1.add(menunewtransaction);

        menuprintpassbook.setText("Print passbook");
        menuprintpassbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuprintpassbookActionPerformed(evt);
            }
        });
        jMenu1.add(menuprintpassbook);

        menudeleteaccount.setText("Delete account");
        menudeleteaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menudeleteaccountActionPerformed(evt);
            }
        });
        jMenu1.add(menudeleteaccount);

        menuexit.setText("Exit");
        menuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexitActionPerformed(evt);
            }
        });
        jMenu1.add(menuexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menunewtransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunewtransactionActionPerformed
        // TODO add your handling code here:
        new Transactiondetails().setVisible(true);
    }//GEN-LAST:event_menunewtransactionActionPerformed

    private void menunewaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunewaccountActionPerformed
        // TODO add your handling code here:
         new Addaccount().setVisible(true);
    }//GEN-LAST:event_menunewaccountActionPerformed

    private void menuprintpassbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuprintpassbookActionPerformed
        // TODO add your handling code here:
        new Printpassbook().setVisible(true);
    }//GEN-LAST:event_menuprintpassbookActionPerformed

    private void menudeleteaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menudeleteaccountActionPerformed
        // TODO add your handling code here:
         new Deleteaccount().setVisible(true);
    }//GEN-LAST:event_menudeleteaccountActionPerformed

    private void menuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menudeleteaccount;
    private javax.swing.JMenuItem menuexit;
    private javax.swing.JMenuItem menunewaccount;
    private javax.swing.JMenuItem menunewtransaction;
    private javax.swing.JMenuItem menuprintpassbook;
    // End of variables declaration//GEN-END:variables
}
